/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "commandsText": "libicns install location",
    "copyrightText": "©2012 John Einselen, Vectorform LLC",
    "done": "done",
    "download": "download",
    "drop": "drop icon files here",
    "dropDetail": "must be .icns format",
    "fail": "file processing failed\nplease try again",
    "iaian7com": "For more information, please visit iaian7.com/dashboard/modicon",
    "label1": "black, white, gamma",
    "label2": "brightness, sat, hue",
    "location1Text": "ImageMagick",
    "location2Text": "libicns",
    "locationText": "ImageMagick install location",
    "nameDetails": "leave blank to overwrite files",
    "nameFileText": "finished file suffix",
    "nameSpriteText": "extra IM commands",
    "nameText": "new file suffix",
    "nameText1": "new file suffix\n(blank will overwrite)",
    "nameText2": "file sheet prefix",
    "new": "new update available!",
    "newVersion": "version number\nversion description",
    "skip": "skip version",
    "success": "file processing successful, busy finishing things up",
    "successDetails": "depending on number of icons\nthis could take a minute",
    "wrong": "wrong file format\nplease try again"
};




