/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "commandsText": "libicns install location",
    "copyrightText": "©2009 John Einselen / Vectorform LLC",
    "done": "done",
    "download": "download",
    "drop": "drop ICNS files here",
    "fail": "file processing failed\nplease try again",
    "iaian7com": "For more information, please visit iaian7.com/dashboard/sheets",
    "label1": "black, white, gamma",
    "label2": "brightness, sat, hue",
    "location1Text": "ImageMagick install location",
    "location2Text": "libicns install location",
    "locationText": "ImageMagick install location",
    "nameFileText": "finished file suffix",
    "nameSpriteText": "extra IM commands",
    "nameText": "finished file suffix (blank overwrites)",
    "nameText2": "file sheet prefix",
    "new": "new update available!",
    "newVersion": "version number\nversion description",
    "skip": "skip version",
    "success": "file processing successful, busy finishing things up",
    "successDetails": "depending on number of icons\nthis could take a minute",
    "wrong": "wrong file format\nplease try again"
};



