/* 
 This file was generated by Dashcode.
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the widget is ready to start
//
function load()
{
	dashcode.setupParts();
	loadPrefs();
	versionCheck();
}

//
// Function: remove()
// Called when the widget has been removed from the Dashboard
//
function remove()
{
	// Stop any timers to prevent CPU usage
	// Remove any preferences as needed
	// widget.setPreferenceForKey(null, dashcode.createInstancePreferenceKey("your-key"));
	erasePrefs();
}

//
// Function: hide()
// Called when the widget has been hidden
//
function hide()
{
	// Stop any timers to prevent CPU usage
	savePrefs();
}

//
// Function: show()
// Called when the widget has been shown
//
function show()
{
	// Restart any timers that were stopped on hide
}

//
// Function: sync()
// Called when the widget has been synchronized with .Mac
//
function sync()
{
	// Retrieve any preference values that you need to be synchronized here
	// Use this for an instance key's value:
	// instancePreferenceValue = widget.preferenceForKey(null, dashcode.createInstancePreferenceKey("your-key"));
	//
	// Or this for global key's value:
	// globalPreferenceValue = widget.preferenceForKey(null, "your-key");
}

//
// Function: showBack(event)
// Called when the info button is clicked to show the back of the widget
//
// event: onClick event from the info button
//
function showBack(event)
{
	var front = document.getElementById("front");
	var back = document.getElementById("back");

	if (window.widget) {
		widget.prepareForTransition("ToBack");
	}

	front.style.display = "none";
	back.style.display = "block";

	if (window.widget) {
		setTimeout('widget.performTransition();', 0);
	}
}

//
// Function: showFront(event)
// Called when the done button is clicked from the back of the widget
//
// event: onClick event from the done button
//
function showFront(event)
{
	var front = document.getElementById("front");
	var back = document.getElementById("back");

	if (window.widget) {
		widget.prepareForTransition("ToFront");
		updatePrefs();
	}

	front.style.display="block";
	back.style.display="none";

	if (window.widget) {
		setTimeout('widget.performTransition();', 0);
	}
}

if (window.widget) {
	widget.onremove = remove;
	widget.onhide = hide;
	widget.onshow = show;
	widget.onsync = sync;
}

// Begin app-specific functions

var wid = widget.identifier;
var prefLevels = loadPref(wid+"levels","16,255,0.8");
var prefHuesat = loadPref(wid+"huesat","100,0,0");
var prefLocation1 = loadPref(wid+"location1","/usr/local/bin/");
var prefLocation2 = loadPref(wid+"location2","/usr/local/bin/");
var prefName = loadPref(wid+"name","_new");

// Preference Saving

function loadPref(key,value) {
	var string = widget.preferenceForKey(key);
	if (string != null) {
		return string;
	} else {
		widget.setPreferenceForKey(value,key);
		return value;
	}
}

function loadPrefs() {
//	alert("ready!");
	document.getElementById("levels").value = prefLevels;
	document.getElementById("huesat").value = prefHuesat;
	document.getElementById("location1").value = prefLocation1;
	document.getElementById("location2").value = prefLocation2;
	document.getElementById("name").value = prefName;
}

function savePref(key,value) {
	if (window.widget) {
		widget.setPreferenceForKey(value,wid+key);
	}
}

function updatePrefs() {
	if (window.widget) {
		widget.setPreferenceForKey(prefLevels,wid+"levels");
		widget.setPreferenceForKey(prefHuesat,wid+"huesat");
		widget.setPreferenceForKey(prefLocation1,wid+"location1");
		widget.setPreferenceForKey(prefLocation2,wid+"location2");
		widget.setPreferenceForKey(prefName,wid+"name");
	}
}

function erasePrefs() {
	if (window.widget) {
		widget.setPreferenceForKey(null,wid+"levels");
		widget.setPreferenceForKey(null,wid+"huesat");
		widget.setPreferenceForKey(null,wid+"location1");
		widget.setPreferenceForKey(null,wid+"location2");
		widget.setPreferenceForKey(null,wid+"name");
	}
}

// Basic Functions

function updateLevels(event) {
	prefLevels = document.getElementById("levels").value;
}

function updateHuesat(event) {
	prefHuesat = document.getElementById("huesat").value;
}

function updateLocation1(event) {
	prefLocation1 = document.getElementById("location1").value;
}

function updateLocation2(event) {
	prefLocation2 = document.getElementById("location2").value;
}

function updateName(event) {
	prefName = document.getElementById("name").value;
}

// Be sure to assign these handlers for the ondragenter and ondragover events on your drop target. These handlers prevent Web Kit from processing drag events so you can handle the drop when it occurs.

function dragEnter(event) {
	event.stopPropagation();
	event.preventDefault();
}

function dragOver(event) {
	event.stopPropagation();
	event.preventDefault();
}

// Define global variables for file names and lists
var uri = [], uriParts = [];

function dragDrop(event) {
	try {
		uri = event.dataTransfer.getData("text/uri-list");
		uri = uri.replace(/file:\/\/localhost/gi, "");
		uri = uri.replace(/\%20/gi, "\\ ");
		uri = uri.split("\n");
		uri = uri.sort(sortAlphaNum);

		var fileListing = "";
		for (i = 0; i < uri.length; i++){
			uriParts[i] = uri[i].match(/(.+?)([^\/]+)(\.\w{3,4})$/);
			fileListing = fileListing+" "+uriParts[i][0];
		}
//		alert("uriParts "+uriParts[1].join("\n"));
//		alert("uri length "+uri.length);
		alert("fileListing1 "+fileListing);

		widget.system("/opt/local/bin/icns2png -x -o "+uriParts[0][1]+fileListing, processImages).outputString;
//			widget.system("/opt/local/bin/icns2png -x -o "+uriParts[1]+" "+uri.join(" "), endHandler).outputString;
//			widget.system("mogrify -level 16,254,0.8 -modulate 100,0 "+uri.join(" "), endHandler).outputString;
//			widget.system("/opt/local/bin/png2icns "+uriParts[1]+"new.icns "+uri.join(" "), endHandler).outputString;

		alert("processing group of files 1");
		showSuccess(event);
	} catch (ex) {
		alert("Problem fetching URI! " + ex);
		showFail(event);
	}

	event.stopPropagation();
	event.preventDefault();
}

function processImages(event) {
	try {
		var fileListing = "";
		for (i = 0; i < uri.length; i++){
			fileListing = fileListing+" "+uriParts[i][1]+uriParts[i][2]+"_*.png";
		}
		alert("fileListing2 "+fileListing);

		widget.system("mogrify -level 16,254,0.8 -modulate 100,0 "+fileListing, createICNS).outputString;

		alert("processing group of files 2");
		showSuccess(event);
	} catch (ex) {
		alert("Problem fetching URI! " + ex);
		showFail(event);
	}
}

function createICNS(event) {
	try {
//		var fileListing = "";
//		for (i = 0; i < uri.length; i++){
//			fileListing = fileListing+" "+uriParts[i][1]+uriParts[i][2]+"_*.png";
//		}
//		alert("fileListing3 "+fileListing);

		for (i = 0; i < uri.length; i++){
			var fileListing = uriParts[i][1]+uriParts[i][2];
			alert("creating ICNS file: "+fileListing+prefName.replace(" ", "\\ ")+".icns ");
			alert("prefName = '"+prefName+"'");
			widget.system("/opt/local/bin/png2icns "+fileListing+prefName.replace(" ", "\\ ")+".icns "+fileListing+"_*.png", endHandler).outputString;
		}

//		widget.system("/opt/local/bin/png2icns "+uriParts[0][1]+"new.icns "+uri.join(" "), endHandler).outputString;

		alert("processing group of files 3");
		showSuccess(event);
	} catch (ex) {
		alert("Problem fetching URI! " + ex);
		showFail(event);
	}
}

function endHandler (output) {
//	alert("output = "+output.outputString);
	showMain();
}

function sortName(a, b) {
	var x = a.toLowerCase();
	var y = b.toLowerCase();
	return (x < y) ? -1 : ((x > y) ? 1 : 0);
}

function sortNumber(a, b) {
	return a - b;
}

function sortAlphaNum(a, b) {
	// the next four lines are designed specifically for OS X file arrays
	// and will need to be modified depending on the situation
	var x = a.split("/");
	var y = b.split("/");
	x = x[x.length-1].replace(/\\\s/g," ").split(/(\d+)/);
	y = y[y.length-1].replace(/\\\s/g," ").split(/(\d+)/);
	for (var i in x) {
		if (x[i] && !y[i] || isFinite(x[i]) && !isFinite(y[i])) {
			return -1;
		} else if (!x[i] && y[i] || !isFinite(y[i]) && isFinite(y[i])) {
			return 1;
		} else if (!isFinite(x[i]) && !isFinite(y[i])) {
			x[i] = x[i].toLowerCase();
			y[i] = y[i].toLowerCase();
			if (x[i] < y[i]) return -1;
			if (x[i] > y[i]) return 1;
		} else {
			x[i] = parseFloat(x[i]);
			y[i] = parseFloat(y[i]);
			if (x[i] < y[i]) return -1;
			if (x[i] > y[i]) return 1;
		}
	}
	return 0;
}



// Key listeners

function selectIt(event) {
	if(event.target){
		event = event.target
	}
//	event.focus();
	event.select();
}

// CurrentView animations

function showMain(event) {
	document.getElementById("stack").object.setCurrentView("main", false, true);
}

function showSuccess(event) {
	document.getElementById("stack").object.setCurrentView("success", true, true);
}

function showFail(event) {
	document.getElementById("stack").object.setCurrentView("fail", true, true);
}

function showWrong(event) {
	document.getElementById("stack").object.setCurrentView("wrong", true, true);
}

function showUpdate(event) {
	document.getElementById("stack").object.setCurrentView("update", true, true);
}

// Get Key Value

function getKeyValue(plist, key) {
	var infoPlist = new XMLHttpRequest();
	infoPlist.open("GET", plist, false);
	infoPlist.send(null);
	infoPlist = infoPlist.responseText.replace(/(<([^>]+)>)/ig,"").replace(/\t/ig,"").split("\n");
	for (var i=0; i<infoPlist.length; i++)
		if (infoPlist[i] == key) return infoPlist[i+1];
	return false;
}

// Auto Update

function versionCheck(event) {
	var request = new XMLHttpRequest();
	var address = "http://iaian7.com/files/dashboard/modicon/version.php?RandomKey=" + Date.parse(new Date());
	request.onload = function() { versionCheckEnd(request); };
	request.open("GET", address);
//	request.setRequestHeader("Cache-Control", "no-cache");
	request.send(null);
}

function versionCheckEnd(request){
	if (request.status == 200) {
		var versions = request.responseText.split("\n");
		var bundleVersion = getKeyValue("Info.plist", "CFBundleVersion");
		var websiteVersion = versions[0];
//		alert("bundleVersion: "+bundleVersion);
//		alert("websiteVersion: "+websiteVersion);

		if (websiteVersion != bundleVersion) {
			document.getElementById("newVersion").innerHTML = "version "+versions[0]+"<br/>"+versions[1];
			return showUpdate();
		} else {
			alert("you have an up to date version");
		}
	} else {
		alert("there's been an error fetching HTTP data");
	}
}

// Download File

function versionDownload() {
	widget.openURL("http://iaian7.com/files/dashboard/modicon/Modicon.zip");
	showMain();
}

// Visit the website

function iaian7(event)
{
	widget.openURL("http://iaian7.com/dashboard/modicon");
}